# Generated by Django 4.2.7 on 2025-06-27 04:31

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographic_intelligence', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='accessibility_score',
            field=models.FloatField(default=0.0, help_text='Transport and infrastructure accessibility score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='lead',
            name='competition_score',
            field=models.FloatField(default=0.0, help_text='Competitive landscape score (higher = less competition)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='lead',
            name='geographic_analysis_date',
            field=models.DateTimeField(blank=True, help_text='When geographic analysis was last performed', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='geographic_score',
            field=models.FloatField(default=0.0, help_text='Geographic intelligence score based on location analysis', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='lead',
            name='headquarters_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic coordinates of company headquarters', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='lead',
            name='market_demand_score',
            field=models.FloatField(default=0.0, help_text='Local market demand and student population score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='lead',
            name='target_neighborhood',
            field=models.ForeignKey(blank=True, help_text='Target neighborhood for investment focus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='geographic_intelligence.neighborhood'),
        ),
        migrations.AddField(
            model_name='lead',
            name='target_universities',
            field=models.ManyToManyField(blank=True, help_text='Universities in target market area', related_name='target_leads', to='geographic_intelligence.university'),
        ),
        migrations.AddField(
            model_name='lead',
            name='university_proximity_score',
            field=models.FloatField(default=0.0, help_text='Proximity to target universities score', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
