# Generated by Django 4.2.7 on 2025-06-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('contacts', '0002_email_campaign_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailcampaign',
            new_name='email_campa_group_i_1367d9_idx',
            old_name='email_campa_group_i_4c6f9e_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcampaign',
            new_name='email_campa_group_i_f49626_idx',
            old_name='email_campa_group_i_8e6a7b_idx',
        ),
        migrations.RenameIndex(
            model_name='emailevent',
            new_name='email_event_message_a990b0_idx',
            old_name='email_event_message_5f8d3b_idx',
        ),
        migrations.RenameIndex(
            model_name='emailevent',
            new_name='email_event_timesta_4bf916_idx',
            old_name='email_event_timesta_2c9f7e_idx',
        ),
        migrations.RenameIndex(
            model_name='emailmessage',
            new_name='email_messa_group_i_46470e_idx',
            old_name='email_messa_group_i_9d2c8f_idx',
        ),
        migrations.RenameIndex(
            model_name='emailmessage',
            new_name='email_messa_group_i_33b067_idx',
            old_name='email_messa_group_i_3e7f2a_idx',
        ),
        migrations.RenameIndex(
            model_name='emailmessage',
            new_name='email_messa_group_i_5d9236_idx',
            old_name='email_messa_group_i_7b9c1e_idx',
        ),
        migrations.RenameIndex(
            model_name='emailtemplate',
            new_name='email_templ_group_i_70558f_idx',
            old_name='email_templ_group_i_6a7d0b_idx',
        ),
        migrations.RenameIndex(
            model_name='emailtemplate',
            new_name='email_templ_group_i_702ed2_idx',
            old_name='email_templ_group_i_f3d8a3_idx',
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='group',
            field=models.ForeignKey(help_text='Group this record belongs to for multi-tenant access control', on_delete=django.db.models.deletion.CASCADE, to='accounts.group'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='group',
            field=models.ForeignKey(help_text='Group this record belongs to for multi-tenant access control', on_delete=django.db.models.deletion.CASCADE, to='accounts.group'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='group',
            field=models.ForeignKey(help_text='Group this record belongs to for multi-tenant access control', on_delete=django.db.models.deletion.CASCADE, to='accounts.group'),
        ),
    ]
