# Generated by Django 4.2.7 on 2025-06-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_email_campa_group_i_4c6f9e_idx_email_campa_group_i_1367d9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier for template (used in code)', max_length=200, null=True, unique=True),
        ),
    ]
