# Generated by Django 4.2.7 on 2025-06-28 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAuditLog_Legacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.UUIDField()),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_audit_log_legacy',
            },
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.AddIndex(
            model_name='assessmentauditlog_legacy',
            index=models.Index(fields=['timestamp'], name='assessment__timesta_55e13f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentauditlog_legacy',
            index=models.Index(fields=['table_name', 'record_id'], name='assessment__table_n_e83207_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentauditlog_legacy',
            index=models.Index(fields=['user'], name='assessment__user_id_304a2f_idx'),
        ),
    ]
